packages:
  - apps/docs
  - apps/figma-mapper
  - apps/playground
  - apps/storybook
  - packages/a11y
  - packages/i18n
  - packages/icons
  - packages/eon-ai-prompts
  - packages/eon-angular
  - packages/eon-core
  - packages/eon-manifest
  - packages/eon-react
  - packages/eon-vue
  - packages/eon-charts-canvas
  - packages/eon-charts
  - packages/eon-charts-core
  - packages/eon-charts-svg
  - packages/styles
  - packages/test-utils
  - packages/tokens
  - packages/utils
  - tools/*

ignoredBuiltDependencies:
  - esbuild
